export default {
  Auchenlarie: {
    Who: 'Mia or any of the team',
    Where: 'On our doorstep',
    'Distance ': '1 mile',
    Rooms:
      'Everything from 2 bed caravan/lodge to self catering cottage with hot tub',
    classification: 'Caravan site with lodges & farm steading conversion',
    Opening: 'All year',
    onenight: 'No but price for 3 nights could be similar to 1 night elsewhere',
    '2 night Minimum':
      'No but price for 3 nights could be similar to 1 night elsewhere',
    'price range': '£70 + per person',
    'Phone number': '01556 506200',
    url: 'www.swalwellholidaygroup.co.uk/',
    Notes: null,
    'Further notes': null,
  },
  Mossyard: {
    Who: 'Joanna or Elaine',
    Where: 'On our doorstep',
    'Distance ': '0.75 miles',
    Rooms: 'Self catering cottages/lodges & caravans',
    classification: 'Caravan site with lodges & farm steading conversion',
    Opening: 'All year',
    onenight: 'No but price for 3 nights could be similar to 1 night elsewhere',
    '2 night Minimum':
      'No but price for 3 nights could be similar to 1 night elsewhere',
    'price range': '£70 + per person',
    'Phone number': '01557 840226',
    url: 'www.mossyard.co.uk',
    Notes:
      'Might not take bookings for certain properties for  high season until 1 year before',
    'Further notes': null,
  },
  'Mossyard Holiday cottages': {
    Who: 'Amy',
    Where: 'On our doorstep',
    'Distance ': 0.75,
    Rooms: 'Holiday cottages',
    classification: 'Self catering',
    Opening: 'All year',
    onenight: 'No but price for 3 nights could be similar to 1 night elsewhere',
    '2 night Minimum':
      'No but price for 3 nights could be similar to 1 night elsewhere',
    'price range': '£70 + per person',
    'Phone number': '07928103490',
    url: null,
    Notes: null,
    'Further notes': null,
  },
  'Cragganmore Holiday House': {
    Who: 'Duncan',
    Where: 'Carrick Shore',
    'Distance ': '10 miles by road - 2 miles as the crow flies',
    Rooms: 'Holiday cottages',
    classification: 'Self catering',
    Opening: 'All year',
    onenight: 'No',
    '2 night Minimum': 'No  ',
    'price range': '£70 + Per person',
    'Phone number': '07966 506873',
    url: 'www.cragganmoreholidayhouse.co.uk',
    Notes: "Stunning holiday house on the shore opposite GG's Yard.",
    'Further notes': null,
  },
  'High Auchenlarie ': {
    Who: 'Liz and Steven',
    Where: 'On our doorstep',
    'Distance ': '1 mile',
    Rooms: 'cottage -sleeps 6',
    classification: 'Self catering',
    Opening: 'All year',
    onenight: null,
    '2 night Minimum': null,
    'price range': null,
    'Phone number': '07730488102',
    url: 'https://www.cottages.com/cottages/high-auchenlarie-uk5949',
    Notes: 'ground floor twin room with shower room',
    'Further notes': null,
  },
  'Bobbin Guest house': {
    Who: 'Helen',
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles East',
    Rooms: '5 rooms',
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£70 + B&B',
    'Phone number': '01557 814229',
    url: 'www.bobbinguesthouse.co.uk',
    Notes: 'Family room can sleep up to 4 people',
    'Further notes': null,
  },
  'Ship Inn': {
    Who: null,
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles East',
    Rooms: null,
    classification: null,
    Opening: null,
    onenight: 'No',
    '2 night Minimum': 'Yes',
    'price range': null,
    'Phone number': null,
    url: null,
    Notes: null,
    'Further notes': null,
  },
  'Murray Arms Hotel': {
    Who: null,
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles East',
    Rooms: '11 Rooms',
    classification: 'Hotel',
    Opening: 'Open all year',
    onenight: 'Not at weekends, but weekdays yes.',
    '2 night Minimum': 'Yes',
    'price range': '£90 B&B',
    'Phone number': '01557 814207',
    url: 'www.murrayarmshotel.co.uk',
    Notes: null,
    'Further notes': null,
  },
  'Cally Palace Hotel ': {
    Who: 'Josephine ',
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles ',
    Rooms: null,
    classification: null,
    Opening: null,
    onenight: null,
    '2 night Minimum': null,
    'price range': null,
    'Phone number': 'O1557814341',
    url: 'www.mcmillanhotels.co.uk',
    Notes: null,
    'Further notes': null,
  },
  'The Waterhouse ': {
    Who: 'Martin and Sharon',
    Where: 'Kirkcudbright',
    'Distance ': '14miles ',
    Rooms: null,
    classification: null,
    Opening: null,
    onenight: null,
    '2 night Minimum': null,
    'price range': null,
    'Phone number': 'O1557331266',
    url: 'waterhousekbt@aol.com',
    Notes: null,
    'Further notes': null,
  },
  'Rusko Stables ': {
    Who: 'Liz Gilbey ',
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles',
    Rooms: '3x double/twin',
    classification: null,
    Opening: null,
    onenight: null,
    '2 night Minimum': null,
    'price range': null,
    'Phone number': null,
    url: 'www.ruskostudio.co.uk/accommodation/',
    Notes: null,
    'Further notes': null,
  },
  Harmony: {
    Who: null,
    Where: 'Carsluith',
    'Distance ': '4 miles West',
    Rooms: '2 rooms',
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£60 B&B',
    'Phone number': '07919651417',
    url: 'http://kimd472004.wixsite.com/harmonybb',
    Notes: null,
    'Further notes': null,
  },
  'Bank of Fleet': {
    Who: 'Kirsty',
    Where: 'Gatehouse of Fleet',
    'Distance ': '4 miles East',
    Rooms: '5 rooms',
    classification: '3* Hotel',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£70 + B&B',
    'Phone number': '01557 814302',
    url: 'www.bankoffleet.co.uk',
    Notes: '1 of rooms is family room which sleeps 4',
    'Further notes': 'Kids 10 and under no charge - 10 - 15 - £10 per night',
  },
  Fludha: {
    Who: 'Jackie',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '6 rooms',
    classification: '5* B&B',
    Opening: 'closed end dec - end feb',
    onenight: 'not at weekends',
    '2 night Minimum': 'min 2 nights',
    'price range': '£100 per room B&B',
    'Phone number': '01557 331443',
    url: 'www.fludha.com',
    Notes: null,
    'Further notes': null,
  },
  Anchorlee: {
    Who: 'Olive',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '4 rooms',
    classification: null,
    Opening: 'Close end Oct until Feb but call',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£80 B&B',
    'Phone number': '01557 330197',
    url: 'www.anchorlee.co.uk/',
    Notes: 'One family room which sleeps 3',
    'Further notes': null,
  },
  'Baytree House': {
    Who: 'Geraldine or Joe',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '4 rooms',
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': 'From £75 per room B&B',
    'Phone number': '01557 330824',
    url: 'www.baytreekirkcudbright.co.uk',
    Notes:
      'Can hire all rooms with use of Drawing room & there is a garden studio flat. ',
    'Further notes': 'Book direct for best prices - not via booking.com',
  },
  'Gladstone House': {
    Who: 'Hillary & Gordon',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '3 rooms',
    classification: '4* B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£80 per room B&B',
    'Phone number': '01557 331734',
    url: 'www.kirkcudbrightgladstone.com',
    Notes: null,
    'Further notes': null,
  },
  Rivergarth: {
    Who: 'Judi & Alan',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '4 rooms',
    classification: '4* B&B',
    Opening: 'Open all year',
    onenight: 'Prefer 2 night...',
    '2 night Minimum': null,
    'price range': '£80 + B&B',
    'Phone number': '01557 332054',
    url: 'www.rivergarth.net',
    Notes: null,
    'Further notes': null,
  },
  Glenholm: {
    Who: 'Laurence & Jennifer',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '3 rooms',
    classification: 'Dont do star ratings but probably best in Kirkcudbright',
    Opening: 'Open all year',
    onenight: 'Possibly',
    '2 night Minimum': null,
    'price range': '£130 + B&B - Dinner from £38',
    'Phone number': '01557 339422',
    url: 'www.glenholmecountryhouse.com',
    Notes: "If you take all rooms the'll be happy to do 1 night",
    'Further notes': 'Confidently the best B&B in Kirkcudbright',
  },
  'High Kirkland Holiday cottage': {
    Who: 'Donald',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '8 rooms',
    classification: 'Self catering',
    Opening: 'Open all year',
    onenight: 'No but price for 3 nights could be similar to 1 night elsewhere',
    '2 night Minimum': null,
    'price range': '£70 + ',
    'Phone number': '07967807375',
    url: 'www.highkirkland.co.uk',
    Notes: 'Hot tub!',
    'Further notes': null,
  },
  Selkirk: {
    Who: 'Chris or Joanna',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '13 rooms',
    classification: 'Hotel',
    Opening: 'Open all year',
    onenight: 'Mid week in winter only',
    '2 night Minimum': 'Yes',
    'price range': '£90 upwards B&B',
    'Phone number': '01557 330402',
    url: 'www.selkirkarmshotel.co.uk',
    Notes: 'Winter mid week 1 night £90+ B&B',
    'Further notes': 'Weekend special Spring/Summer - £92.50 Upward B&B',
  },
  'Arden House': {
    Who: 'Billy',
    Where: 'Kirkcudbright',
    'Distance ': '14 miles South East',
    Rooms: '8 rooms',
    classification: 'Hotel',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£65 - £85 B&B',
    'Phone number': '01557 330544',
    url: 'www.arden-kirkcudbright.co.uk',
    Notes: 'Also have 1 x Single room',
    'Further notes': null,
  },
  'Stables Guest House': {
    Who: 'Jacqui',
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: '6 rooms',
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': 'From £80 B&B',
    'Phone number': null,
    url: null,
    Notes: null,
    'Further notes': null,
  },
  Rowallan: {
    Who: 'Julie & Rob',
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: '5 rooms',
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': 'From £71 B&B',
    'Phone number': '01671 402520',
    url: 'www.rowallan.co.uk/',
    Notes: null,
    'Further notes': null,
  },
  'Flower Bank': {
    Who: 'Mick & Di',
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: null,
    classification: 'B&B',
    Opening: null,
    onenight: null,
    '2 night Minimum': null,
    'price range': null,
    'Phone number': null,
    url: 'www.flowerbankgh.com/',
    Notes: null,
    'Further notes': null,
  },
  'Creebridge House': {
    Who: null,
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: '14 rooms',
    classification: '3* Hotel',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£100 B&B or £140 DBB',
    'Phone number': '01671 402121',
    url: 'www.creebridge.co.uk',
    Notes: '3 rooms are family rooms',
    'Further notes': 'They offer 3 night special breaks from £390 DBB',
  },
  'Crown Hotel': {
    Who: 'Aaron or Laura',
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: '8 rooms',
    classification: '3* Hotel',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': 'From £80 B&B',
    'Phone number': '01671 402727',
    url: 'www.the-crown-hotel.com',
    Notes: null,
    'Further notes': null,
  },
  'Kirroughtree House Hotel': {
    Who: 'Morag',
    Where: 'Newton Stewart',
    'Distance ': '15 miles West',
    Rooms: '16 rooms',
    classification: '3* Hotel',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': '£105 - £165 B&B',
    'Phone number': '01671 402141',
    url: 'www.kirroughtreehousehotel.co.uk',
    Notes: null,
    'Further notes': null,
  },
  'Muirfad Farmhouse ': {
    Who: 'Sue ',
    Where: 'Newton Stewart ',
    'Distance ': '9 miles ',
    Rooms: null,
    classification: 'B&B',
    Opening: 'Open all year',
    onenight: 'YES!!!',
    '2 night Minimum': null,
    'price range': null,
    'Phone number': 'O1671820536',
    url: 'muirfadfarmhouse7ba@btinternet.co.uk',
    Notes: null,
    'Further notes': null,
  },
};
